# Konfiguracja API i bezpieczeństwa
api:
  key: "{{ env.API_KEY }}"
  timeout: 30
  max_retries: 3

security:
  enable_api_auth: true
  allowed_ips: []  # Puste = wszystkie IP
  session_timeout: 3600  # 1 godzina

# Konfiguracja dla różnych środowisk
environments:
  development:
    api_key: "CHANGE_ME_DEV_API_KEY_2025"
    debug: true
    
  production:
    api_key: "{{ env.API_KEY }}"
    debug: false
    
  testing:
    api_key: "CHANGE_ME_TEST_API_KEY_2025"
    debug: true
