# Konfiguracja kolumn danych z Google Sheet
# Podział na kolumny selekcji i kolumny informacyjne

# Kolumny używane w selekcji (nie zmieniaj bez konsultacji)
selection_columns:
  country: "Country"
  quality_rating: "Quality Rating (out Of 13)"
  yield: "Yield"
  dividend_growth_streak: "Dividend Growth Streak (Years)"
  sp_credit_rating: "S&P Credit Rating"
  dk_valuation_rating: "DK Valuation Rating"

# Kolumny informacyjne (możesz edytować)
informational_columns:
  date_edited: "Date Edited"
  company: "Company"
  sector: "Sector"
  current_price: "Current Price"  # Kolumna Z - cena aktualna w dolarach
  historical_fair_value: "Historical Fair Value"  # Kolumna AA - Historical Fair Value w procentach (ale to są dolary)
  market_cap_billion: "Market Cap (Billion)"  # Kolumna DB - miliardy dolarów
  # Możesz dodać więcej kolumn informacyjnych tutaj
  # current_price: "Current Price"
  # payout_ratio: "Payout Ratio"
  # debt_capital: "Debt/Capital"

# Kolumna z tickerem (używana do identyfikacji spółek)
ticker_column: "Ticker" 