# Reguły selekcji spółek - Etap 1
# Te reguły są stosowane do danych z Google Sheet

selection_rules:
  country:
    column: "Country"
    operator: "in"
    values: ["USA", "UK", "Canada"]
  
  quality_rating:
    column: "Quality Rating (out Of 13)"
    operator: "in"
    values: ["13.00", "12.00"]
  
  yield:
    column: "Yield"
    operator: ">="
    value: "4%"
  
  dividend_growth_streak:
    column: "Dividend Growth Streak (Years)"
    operator: ">="
    value: "15.00"
  
  sp_credit_rating:
    column: "S&P Credit Rating"
    operator: "complex"
    allowed_patterns: ["A*", "BBB+", "BBB"]
    excluded_values: ["BBB-", "NA"]
  
  dk_rating:
    column: "DK Rating"
    operator: "in"
    values: ["Potential Good Buy or Better"]
  
 